---
title: "phyloseq for Lyon Pilot"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(dada2)
library(phyloseq)
library(data.table)
library(Biostrings)
library(ape)
library(plyr)
library(vegan)
library(ggplot2)
theme_set(theme_bw())   ###optional
```

phyloseq-ize Data already in R
```{r}
dada2_output <- fread("data/seqtab_nochim.csv") |> as.data.frame()
asv2seq <- fread("data/asv_seq_table.csv") |> as.data.frame()
asv2tax <- fread("data/arthropoda_lyon_pilot.csv") |> as.data.frame()
lyon_meta <- fread("data/lyon_metadata.csv") |> as.data.frame()

# replace column names of `data2_output` with ASV names rather than seqs
colnames(dada2_output)[-1] <- 
    asv2seq$ASV_ID[match(colnames(dada2_output)[-1], asv2seq$Sequence)]

# make row names of `dada2_output` be sample ID
rownames(dada2_output) <- dada2_output[, 1]
dada2_output <- dada2_output[, -1]

# trim down ASVs to only arthropods
# note: `asv2tax` only has arthropods, so subsetting to the ASVs in `asv2tax`
#        will leave us with only arthropods
dada2_output <- dada2_output[, asv2tax$asv_id]

# remove empty rows from `lyon_meta`
lyon_meta <- lyon_meta[lyon_meta$Sample != "", ]

# rownames of sample data should be same as rownames of otu table
rownames(lyon_meta) <- lyon_meta$Sample
samp_data <- lyon_meta[, names(lyon_meta) != "Sample"] |> sample_data()

# rownames of taxa table must be same as colnames of otu table
rownames(asv2tax) <- asv2tax$asv_id
tax_tab <- asv2tax[, !(names(asv2tax) %in% 
                           c("asv_id", "count", "percent_match"))] |>
    as.matrix() |>
    tax_table()

# make a DNAStringSet out of the sequences
lyon_seqs <- DNAStringSet(asv2seq$Sequence)
names(lyon_seqs) <- asv2seq$ASV_ID

# make the otu table
asvtab <- otu_table(dada2_output, taxa_are_rows = FALSE)

# put it all together
ps <- phyloseq(asvtab, samp_data, tax_tab, lyon_seqs)

```

Alpha diversity
```{r}
plot_richness(ps, measures=c("Chao1", "Shannon"), x="substrate", color="method", shape="site_type")
```



Ordination plot for ASV's
```{r}
#ps_ord <- ordinate(ps, "NMDS", "bray")      ###troubleshoot data after failing to ordinate

#sample_sums(ps)     ###revealed some samples with sum zero, need to remove those
ps <- prune_samples(sample_sums(ps) > 0, ps)    ###remove them

#anyNA(otu_table(ps))    ###false, so that's good

#try again
ps_ord <- ordinate(ps, "NMDS", "bray")
plot_ordination(ps, ps_ord, type="taxa", color="order", title="OTUs (Distance metric: Bray)") +
    facet_wrap(~class) +
    xlim(-0.1, 1) +
    ylim(-0.1, 0.6)

#length(unique(asv2tax$class))      ###there are 13 classes being displayed
#length(unique(asv2tax$order))      ###there are 42 orders being displayed

#canberra good for emphasizing low-abundance taxa
ps_ord <- ordinate(ps, "NMDS", "canberra")
plot_ordination(ps, ps_ord, type="taxa", color="order", title="OTUs (Distance metric: Canberra)") +
    facet_wrap(~class)

#check ordination
ps_ord$stress

#check distance matrix
dist_matrix <- vegdist(otu_table(ps), method = "bray")
summary(dist_matrix)

#try transforming data -- proportional
ps_transformed_proportional <- transform_sample_counts(ps, function(x) x / sum(x))
ps_tp_ord <- ordinate(ps_transformed_proportional, "NMDS", "bray")
plot_ordination(ps, ps_tp_ord, type="split", color="class", shape="site_name", title="bilot (Distance metric: Bray, Transformation: Proportional)", label = "station") +
    geom_point(size=3)

#try transforming data -- hellinger
otu_hellinger <- decostand(otu_table(ps), method = "hellinger")
otu_hellinger <- otu_table(otu_hellinger, taxa_are_rows = FALSE)
taxa_names(otu_hellinger) <- taxa_names(tax_table(ps))
ps_transformed_hellinger <- phyloseq(otu_hellinger, sample_data(ps), tax_table(ps))
ps_th_ord <- ordinate(ps_transformed_hellinger, "NMDS", "bray")
plot_ordination(ps, ps_th_ord, type="split", color="class", shape="site_name", title="bilot (Distance metric: Bray, Transformation: Hellinger)", label = "station") +
    geom_point(size=3)

#log transformation? 
#transform_sample_counts(ps, function(x) log1p(x))

#centered log-ratio transformation? 
#transform(ps, "clr")
```


Ordination plot for samples
```{r}
plot_ordination(ps, ps_ord, type="samples", color="site_name", shape="substrate", title="Samples (Distance metric: Bray)") +
    facet_wrap(~method) +
    geom_point(size=2)
```



Display sample and OTUs in side by side panels to compare
```{r}
plot_ordination(ps, ps_ord, type="split", color="family", shape="site_name", title="bilot (Distance metric: Bray)", label = "station") +
    geom_point(size=3)
```
















