---
title: "phyloseq figuring"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Load packages

```{r}
library(dada2)
library(phyloseq)
library(data.table)
library(Biostrings)
library(ape)
```

Load data

```{r}
dada2_output <- fread("data/seqtab_nochim.csv") |> as.data.frame()
asv2seq <- fread("data/asv_seq_table.csv") |> as.data.frame()
asv2tax <- fread("data/arthropoda_lyon_pilot.csv") |> as.data.frame()
lyon_meta <- fread("data/lyon_metadata.csv") |> as.data.frame()
```

Clean up data

```{r}
# replace column names of `data2_output` with ASV names rather than seqs
colnames(dada2_output)[-1] <- 
    asv2seq$ASV_ID[match(colnames(dada2_output)[-1], asv2seq$Sequence)]

# make row names of `dada2_output` be sample ID
rownames(dada2_output) <- dada2_output[, 1]
dada2_output <- dada2_output[, -1]

# trim down ASVs to only arthropods
# note: `asv2tax` only has arthropods, so subsetting to the ASVs in `asv2tax`
#        will leave us with only arthropods
dada2_output <- dada2_output[, asv2tax$asv_id]

# remove empty rows from `lyon_meta`
lyon_meta <- lyon_meta[lyon_meta$Sample != "", ]
```



Wrap it all up in a phyloseq object

```{r}
# prep data for how phyloseq likes it

# rownames of sample data should be same as rownames of otu table
rownames(lyon_meta) <- lyon_meta$Sample
samp_data <- lyon_meta[, names(lyon_meta) != "Sample"] |> sample_data()

# rownames of taxa table must be same as colnames of otu table
rownames(asv2tax) <- asv2tax$asv_id
tax_tab <- asv2tax[, !(names(asv2tax) %in% 
                           c("asv_id", "count", "percent_match"))] |>
    as.matrix() |>
    tax_table()

# make a DNAStringSet out of the sequences
lyon_seqs <- DNAStringSet(asv2seq$Sequence)
names(lyon_seqs) <- asv2seq$ASV_ID

# make the otu table
asvtab <- otu_table(dada2_output, taxa_are_rows = FALSE)

# put it all together
ps <- phyloseq(asvtab, samp_data, tax_tab, lyon_seqs)
```

## Rarefaction

First remove samples we donʻt want to look at through rarefaction:

```{r}
ps4rar <- subset_samples(ps, method %in% c("Gauze", "Roller") & 
                             site_name != "Lab" &
                             substrate != "Control" & 
                             cleaned_extract == "no")

# add a replicate column for grouping purposes
d <- sample_data(ps4rar)
d$rep <- gsub("-gauze.*|-roller.*", "", rownames(d))
sample_data(ps4rar) <- d

# now merge phyloseq object by rep
# note: must use merge_samples2 from speedyseq to merge categorical sample data 
ps4rar_merged <- speedyseq::merge_samples2(ps4rar, "rep")

```

Now we can rarefy 

```{r}
# define a custom rarefaction function
#' @param x is a phyloseq object

rfy <- function(x) {
    dat <- otu_table(x) |> unclass()
    dat <- dat[, colSums(dat) > 0] # no need taxa where read freq is 0
    
    zeros <- rowSums(dat) == 0
    dat <- dat[!zeros, ]
    
    nspp_est <- ncol(dat)
    
    res <- lapply(1:nrow(dat), function(i) {
        # m = s
        # d = n
        # this_dat = X_i
        
        this_dat <- dat[i, ]
        d <- sum(this_dat)
        s <- 2^seq(log(1, 2), log(d, 2), by = 1) 
        s <- c(s, d)
        
        nspp <- sum(this_dat > 0)
        
        mvar <- sapply(s, function(m) {
            alpha <- exp(lchoose(d - this_dat[this_dat > 0], m) - lchoose(d, m))
            
            nspp_m <- nspp - sum(alpha)
            nspp_v <- sum((1 - alpha)^2) - nspp_m^2 / nspp_est
            
            return(c(nspp_m = nspp_m, nspp_v = nspp_v))
        })
        
        mvar <- t(mvar) |> as.data.frame()
        mvar <- cbind(samp = rownames(dat)[i], depth = s, mvar)
        
        return(mvar)
    })
    
    res <- do.call(rbind, res)
    
    res$nspp_ciLO <- res$nspp_m - 2 * sqrt(res$nspp_v)
    res$nspp_ciHI <- res$nspp_m + 2 * sqrt(res$nspp_v)
    
    return(res)
}

rfy_res <- rfy(ps4rar_merged)
```

Finally we can plot it:

```{r}
library(ggplot2)

ggplot(rfy_res, aes(x = depth, y = nspp_m, color = samp)) +
    geom_line() +
    scale_x_continuous(trans = "log10")

```



```{r}
foo <- prune_samples(sample_sums(ps4rar_merged) > 0, ps4rar_merged) |>
    tax_glom("order")

doo <- ordinate(foo, "NMDS", "bray")
plot_ordination(foo, doo, color = "site_name", shape = "substrate")

plot_heatmap(ps4rar_merged, sample.order = "site_name")

```
